# Instantiating the 'tigas' object with its physical network address
[my_targets]
tigas ansible_host=192.168.43.1 ansible_user=u0_a611 ansible_port=8022 ansible_python_interpreter=/data/data/com.termux/files/usr/bin/python
